from pydantic import BaseModel
# Pydantic models for request and response validation
class Employee(BaseModel):
    employee_id: int  # Auto-generated by DB, so no need to provide it on create
    first_name: str
    last_name: str
    email: str
    salary: int

    class Config:
        orm_mode = True  # This allows the Pydantic model to work with SQLAlchemy models

class EmployeeCreate(BaseModel):
    first_name: str
    last_name: str
    email: str
    salary: int
    
class CampaignBase(BaseModel):
    name: str
    budget: float
    platform: str

class CampaignCreate(CampaignBase):
    pass

class CampaignResponse(CampaignBase):
    id: int
    
# Placeholder schemas based on ERD resources

class CampaignBase(BaseModel):
    name: str
    budget: float
    platform: str

class CampaignCreate(CampaignBase):
    pass

class CampaignResponse(CampaignBase):
    id: int


class AdBase(BaseModel):
    campaign_id: int
    platform: str
    creative_type: str

class AdCreate(AdBase):
    pass

class AdResponse(AdBase):
    id: int


class AudienceBase(BaseModel):
    age: int
    gender: str
    location: str
    interests: str

class AudienceCreate(AudienceBase):
    pass

class AudienceResponse(AudienceBase):
    id: int


class PredictionBase(BaseModel):
    campaign_id: int
    predicted_ctr: float
    predicted_conversion_rate: float

class PredictionCreate(PredictionBase):
    pass

class PredictionResponse(PredictionBase):
    id: int


class TrainingDatasetBase(BaseModel):
    platform: str
    budget: float
    duration_days: int
    ctr: float
    conversion_rate: float

class TrainingDatasetCreate(TrainingDatasetBase):
    pass

class TrainingDatasetResponse(TrainingDatasetBase):
    id: int
    