from pydantic import BaseModel
# Pydantic models for request and response validation
class Employee(BaseModel):
    employee_id: int  # Auto-generated by DB, so no need to provide it on create
    first_name: str
    last_name: str
    email: str
    salary: int

    class Config:
        orm_mode = True  # This allows the Pydantic model to work with SQLAlchemy models

class EmployeeCreate(BaseModel):
    first_name: str
    last_name: str
    email: str
    salary: int
    
class CampaignBase(BaseModel):
    name: str
    budget: float
    platform: str

class CampaignCreate(CampaignBase):
    pass

class CampaignResponse(CampaignBase):
    id: int
    
# Placeholder schemas based on ERD resources

class CampaignBase(BaseModel):
    name: str
    budget: float
    platform: str

class CampaignCreate(CampaignBase):
    pass

class CampaignResponse(CampaignBase):
    id: int


class AdBase(BaseModel):
    campaign_id: int
    platform: str
    creative_type: str

class AdCreate(AdBase):
    pass

class AdResponse(AdBase):
    id: int


class AudienceBase(BaseModel):
    age: int
    gender: str
    location: str
    interests: str

class AudienceCreate(AudienceBase):
    pass

class AudienceResponse(AudienceBase):
    id: int


class PredictionBase(BaseModel):
    campaign_id: int
    predicted_ctr: float
    predicted_conversion_rate: float

class PredictionCreate(PredictionBase):
    pass

class PredictionResponse(PredictionBase):
    id: int


class TrainingDatasetBase(BaseModel):
    platform: str
    budget: float
    duration_days: int
    ctr: float
    conversion_rate: float

class TrainingDatasetCreate(TrainingDatasetBase):
    pass

class TrainingDatasetResponse(TrainingDatasetBase):
    id: int
    
from typing import Any, Dict, List, Optional

class MetaEnumsResponse(BaseModel):
    platforms: List[str]
    campaign_intents: List[str]
    cta_types: List[str]
    audience_temperature: List[str]
    devices: List[str]
    customer_types: List[str]
    product_types: List[str]
    regions: List[str]
    age_bands: List[str]


class StatusResponse(BaseModel):
    status: str
    backend: str
    model_version: str
    max_creatives: int
    upload_limits: Dict[str, Any]
    prefect_available: bool


class PredictionPreviewRequest(BaseModel):
    platform: str
    campaign_intent: str
    product_type: str
    cta_type: str
    audience_temperature: str
    customer_type: str
    budget: float
    duration_days: int
    creative_count: Optional[int] = 1


class RecommendationBlock(BaseModel):
    rank: int
    primary_kpi: str
    score: float
    hint: str


class PredictionPreviewResponse(BaseModel):
    run_id: str
    status: str
    model_version: str
    campaign_intent: str
    target_metric: str  # ctr | conversion_rate | reach_score
    target_label: str
    predicted_tier: Optional[str] = None
    prediction_confidence: Optional[float] = None
    recommendations: List[RecommendationBlock]
    input_summary: Dict[str, Any]


class PredictionRunResponse(PredictionPreviewResponse):
    pass